# Generated by Django 4.1.4 on 2023-01-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_category_menuitem_delete_menu_remove_booking_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reservation_date',
            field=models.DateField(default=None),
        ),
    ]
