# Generated by Django 4.1.4 on 2022-12-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(default='No Description', max_length=1000),
        ),
    ]
